import React, { useState, useRef, useEffect } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function TopNav({ metrics, demoMode, setDemoMode, setShowSources, onSearch, interventions = [] }: { metrics?: any, demoMode: boolean, setDemoMode: any, setShowSources: any, onSearch: any, interventions?: any[] }) {
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchFailed, setSearchFailed] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const dropdownRef = useRef(null);
  
  useEffect(() => {
    const handleClick = (e) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) setDropdownOpen(false);
    };
    document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, []);

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    if (!searchQuery) return;
    const found = onSearch(searchQuery);
    if (!found) {
      setSearchFailed(true);
      setTimeout(() => setSearchFailed(false), 2000);
    }
  };

  const generateReport = async () => {
    setIsGenerating(true);
    
    // Aggregates
    const total = interventions.length;
    const verified = interventions.filter(i => i.status_badge === 'VERIFIED').length;
    const review = interventions.filter(i => i.status_badge === 'REVIEW').length;
    const flagged = interventions.filter(i => i.status_badge === 'FLAGGED').length;
    
    const hydroFails = interventions.filter(i => i.flag_hydro).length;
    const conflictFails = interventions.filter(i => i.flag_conflict).length;
    
    // Create hidden container
    const container = document.createElement('div');
    container.style.position = 'absolute';
    container.style.left = '-9999px';
    container.style.top = '0';
    container.style.width = '800px';
    container.style.backgroundColor = '#ffffff';
    container.style.fontFamily = 'sans-serif';
    container.style.color = '#1e293b';
    container.style.padding = '40px';
    
    // HTML Structure
    container.innerHTML = `
      <div style="position: relative; width: 100%;">
        ${demoMode ? '<div style="position: absolute; top: 0; right: 0; color: #f59e0b; font-weight: bold; border: 2px solid #f59e0b; padding: 4px 8px; border-radius: 4px; font-size: 12px; letter-spacing: 2px; transform: rotate(15deg);">DEMO MODE</div>' : ''}
        
        <!-- Header -->
        <div style="border-bottom: 2px solid #e2e8f0; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="color: #0f172a; margin: 0 0 10px 0; font-size: 28px; font-weight: 900;">WDC-PMKSY IWMP Summary Report</h1>
          <div style="font-size: 18px; color: #475569; font-weight: 700;">Project: PUNE-WDC-1</div>
          <div style="font-size: 14px; color: #64748b; margin-top: 5px;">Generated by Watershed Evidence Engine</div>
          <div style="font-size: 12px; color: #94a3b8; margin-top: 5px;">Department of Land Resources, Ministry of Rural Development, Govt. of India</div>
          <div style="font-size: 12px; color: #94a3b8; margin-top: 5px;">Date: ${new Date().toLocaleDateString()}</div>
        </div>

        <!-- Exec Summary -->
        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 18px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 15px;">Executive Summary</h2>
          <p style="font-size: 14px; line-height: 1.6; color: #334155; margin: 0;">
            This report summarizes the spatial and analytical verification of <strong>${total}</strong> structural interventions within the PUNE-WDC-1 watershed project. 
            Out of the total structures evaluated, <strong>${verified}</strong> have been marked as Verified, <strong>${review}</strong> require further Review, and <strong>${flagged}</strong> have been Flagged due to critical anomalies. 
            Notably, the Evidence Engine detected <strong>${hydroFails}</strong> hydrological placement failures and <strong>${conflictFails}</strong> instances of field-vs-satellite evidence conflicts, prioritizing these for immediate field inspection.
          </p>
        </div>

        <!-- Study Area -->
        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 18px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 15px;">Study Area</h2>
          <div style="display: flex; gap: 20px;">
            <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; flex: 1;">
              <div style="font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; margin-bottom: 5px;">Watershed / Taluka</div>
              <div style="font-size: 16px; font-weight: 800; color: #0f172a;">Khed Taluka, Pune</div>
            </div>
            <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; flex: 1;">
              <div style="font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; margin-bottom: 5px;">Total Area</div>
              <div style="font-size: 16px; font-weight: 800; color: #0f172a;">24,000 ha</div>
            </div>
            <div style="background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 8px; flex: 1;">
              <div style="font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; margin-bottom: 5px;">Village Count</div>
              <div style="font-size: 16px; font-weight: 800; color: #0f172a;">14 Villages</div>
            </div>
          </div>
        </div>

        <!-- Data Sources -->
        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 18px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 15px;">Satellite & Ancillary Data</h2>
          <ul style="font-size: 13px; line-height: 1.6; color: #334155; padding-left: 20px; margin: 0;">
            <li style="margin-bottom: 5px;"><strong>Administrative Boundary:</strong> True Khed Taluka catchment polygon. <span style="color: #16a34a; font-weight: bold;">(Real Data)</span></li>
            <li style="margin-bottom: 5px;"><strong>Terrain & Hydrology:</strong> SRTM 30m DEM and actual stream networks via flow accumulation. <span style="color: #16a34a; font-weight: bold;">(Real Data)</span></li>
            <li style="margin-bottom: 5px;"><strong>Vegetation (SAVI) & Water (MNDWI):</strong> Analytical change grids computed synthetically based on proximity and terrain. <span style="color: #ea580c; font-weight: bold;">(Demo Mode Synthetic)</span></li>
            <li style="margin-bottom: 5px;"><strong>Intervention Metadata:</strong> DRISHTI schema structure aligned with Bhuvan WDC 2.0 portal, generating synthetic conflict scores. <span style="color: #ea580c; font-weight: bold;">(Demo Mode Synthetic)</span></li>
          </ul>
        </div>

        <!-- Site-wise Changes -->
        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 18px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 15px;">Site-wise Changes & Verifications</h2>
          <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
            <thead>
              <tr style="background: #f1f5f9; text-align: left;">
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Work Code</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Location</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Type</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Impact</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Status</th>
                <th style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: #475569; text-transform: uppercase;">Reason</th>
              </tr>
            </thead>
            <tbody>
              ${interventions.map(i => `
                <tr>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; color: #334155; font-family: monospace;">${i.work_code || 'N/A'}</td>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; color: #334155;">${i.location || 'N/A'}</td>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; color: #334155;">${i.type}</td>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; color: #334155; font-weight: bold;">${i.score_impact ? (i.score_impact*10).toFixed(1) : '-'}</td>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; font-weight: bold; color: ${i.status_badge === 'VERIFIED' ? '#16a34a' : (i.status_badge === 'FLAGGED' ? '#dc2626' : '#ea580c')}">${i.status_badge}</td>
                  <td style="padding: 8px; border: 1px solid #cbd5e1; color: #64748b; font-size: 10px;">${i.priority_reason || '-'}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
        </div>

        <!-- Conclusions -->
        <div>
          <h2 style="color: #0f172a; font-size: 18px; font-weight: 800; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 15px;">Conclusions & Recommendations</h2>
          <p style="font-size: 14px; line-height: 1.6; color: #334155; margin: 0;">
            Based on multi-layer spatial analysis, <strong>${flagged + review}</strong> sites require urgent physical verification or structural auditing. Priority should be given to interventions exhibiting severe evidence conflicts and hydrological misalignments. The integrity of the watershed implementation remains largely positive across verified clusters, but corrective action is mandated for flagged coordinates.
          </p>
        </div>
      </div>
    `;

    document.body.appendChild(container);

    try {
      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        logging: false
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      
      // Footer watermark
      if (demoMode) {
        pdf.setTextColor(200, 200, 200);
        pdf.setFontSize(10);
        pdf.text("DEMO MODE - SYNTHETIC ANALYTICAL DATA", pdfWidth / 2, 290, { align: "center" });
      }

      pdf.save(`WDC-PMKSY-PUNE-WDC-1-Report-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (err) {
      console.error('Failed to generate PDF:', err);
    } finally {
      document.body.removeChild(container);
      setIsGenerating(false);
    }
  };

  return (
    <header className="bg-white text-slate-800 flex items-center justify-between px-6 py-3 shrink-0 shadow-sm border-b border-slate-200 relative z-40 gap-4 overflow-visible">
      <div className="flex items-center gap-4 shrink-0">
        <div className="font-black text-xl tracking-tight text-slate-800 flex items-center gap-2">
          <span className="text-teal-600">💧</span> WDC-PMKSY
        </div>
        <div className="h-5 w-px bg-slate-300"></div>
        <div className="text-sm font-extrabold text-slate-500 tracking-wide uppercase">PUNE-WDC-1</div>
      </div>

      <div className="flex-1 flex justify-center min-w-[200px] max-w-md shrink relative">
        <form onSubmit={handleSearchSubmit} className="relative w-full">
          <input 
            type="text" 
            placeholder="Search work codes..." 
            value={searchQuery}
            onChange={e => setSearchQuery(e.target.value)}
            className={`w-full bg-slate-50 text-slate-800 border rounded-full px-4 py-2 text-sm focus:outline-none focus:ring-1 shadow-inner placeholder-slate-400 ${searchFailed ? 'border-red-500 focus:border-red-500 focus:ring-red-500 bg-red-50' : 'border-slate-300 focus:border-teal-500 focus:ring-teal-500'}`} 
          />
          <button type="submit" className="absolute right-3 top-2 text-slate-400 hover:text-teal-600">🔍</button>
        </form>
        {searchFailed && <div className="absolute top-10 left-0 bg-red-100 text-red-700 px-3 py-1 rounded shadow text-xs font-bold border border-red-200">No work code found</div>}
      </div>

      <div className="flex items-center gap-4 shrink-0">
        <div className="hidden md:flex items-center gap-4">
          <button onClick={() => setShowSources(true)} className="text-xs font-extrabold text-slate-500 hover:text-slate-800 uppercase tracking-wider transition-colors">
            Data Sources
          </button>
          <button 
            onClick={generateReport} 
            disabled={isGenerating}
            className={`bg-teal-600 hover:bg-teal-500 text-white text-xs font-bold uppercase tracking-wider px-4 py-2 rounded shadow transition-colors flex items-center gap-2 ${isGenerating ? 'opacity-75 cursor-wait' : ''}`}
          >
            <span>📄</span> {isGenerating ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
        <label className="flex items-center gap-2 text-xs font-bold bg-slate-50 px-3 py-1.5 rounded-full border border-slate-200 cursor-pointer whitespace-nowrap shadow-sm">
          <span className={demoMode ? "text-amber-600" : "text-slate-500"}>DEMO MODE</span>
          <input type="checkbox" checked={demoMode} onChange={(e) => setDemoMode(e.target.checked)} className="accent-amber-500 w-3 h-3" />
        </label>
        <div className="w-9 h-9 rounded-full bg-teal-100 flex items-center justify-center text-sm font-extrabold text-teal-800 border border-teal-200 shadow-sm shrink-0">NR</div>
      </div>
    </header>
  );
}
